#! /usr/bin/env python
# -*- coding: utf-8 -*-
from cycler import cycler

# SET UP PLOT PARAMETERS FOR ALL PLOTS
pars = { 'backend'		: 'pdf',
	 'text.usetex'		: True,
	 'xtick.labelsize'	: 24,
	 'xtick.major.pad'	: 10,
	 'xtick.major.size'	: 10,
	 'xtick.minor.size'	: 5,
	 'xtick.major.width'    : 0.8,
	 'xtick.minor.width'    : 0.6,
	 'ytick.labelsize'      : 24,
         'ytick.major.pad'      : 8,
         'ytick.major.size'     : 10,
         'ytick.minor.size'     : 5,
         'ytick.major.width'    : 2.5,   
         'ytick.minor.width'    : 1.25,
	 'legend.borderpad'     : 0.25,
	 'legend.labelspacing'  : 0.5,
	 'legend.borderaxespad' : 0.75,
	 'legend.fontsize'	: 24,
	 'legend.fancybox'	: True,
	 'legend.shadow'	: False,
	 'legend.frameon'	: True,
	 'lines.markersize'	: 7,
	 'lines.linewidth'	: 3,
	 'font.family'		: 'serif',
	 'font.sans-serif'	: 'Helvetica',
	 'font.serif'		: 'cmr10',
	 'font.size'		: 24,
	 'axes.facecolor'	: 'white',
	 'axes.edgecolor'	: 'black',
	 'axes.linewidth'	: 1.0,
	 'axes.labelweight'	: 'normal',
	 'axes.labelcolor'	: 'black',
	 'axes.labelsize'	: 24,
	 'axes.axisbelow'	: 'True',
	 'axes.formatter.limits': (-4,4),
	 'axes.prop_cycle'	: cycler('color', ['#293352', '#A51C30', '#4E84C4', '#52854C', '#D16103', '#C4961A', '#FFD86D'])
}
